/**
 * 
 */
package hue10.ShiftPuzzle;

/**
 * @author ElisabethElisabeth Gombkötö
 *17.01.2017WS_2016
 */
public class EffectiveBranchingFactorCalculator {
	
	/**
	 * Informal Definitions
*
* The branching factor is the number of successors generated by a given node.
*The effective branching factor is the number of successors generated by a "typical" node for a given search problem.
*Formal Definition
*
*N: Total number of nodes processed.
*d: Depth at which the solution node was found.
*b*: Effective branching factor.
*N = b* + (b*)2 + ... + (b*)d
*Calculating b*

No closed-form solution
Solution 1: A Close Guess
N^(1/d)
	 * @param n
	 * @param d
	 * @return
	 */
	
	public static double calculateNoCloseForm(double n, double d){
		  double solution = Math.pow(n, 1/d);
		  return solution;
	}
}
